# Generated by Django 5.1.1 on 2024-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='home page name')),
                ('img', models.ImageField(upload_to='media', verbose_name='home page img')),
            ],
        ),
    ]
