# Generated by Django 5.1.1 on 2024-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About1', models.TextField(verbose_name='about1')),
                ('About2', models.TextField(verbose_name='about2')),
                ('img', models.ImageField(upload_to='', verbose_name='about')),
            ],
        ),
    ]
