# Generated by Django 5.1.1 on 2024-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='paragraf',
            field=models.TextField(default=None, max_length=100, verbose_name='paragraf'),
            preserve_default=False,
        ),
    ]
